### ISSUE TITLE
Yet another MD5 in Swift

### ISSUE THREAD

**Issue by onmyway133** [3lvis/MD5#1]
Hi, I just implement this https://github.com/onmyway133/SwiftHash. You may want to take a look 😉

**Comment by 3lvis** [comment]
Thanks! I'll copy over the implementation and add attribution.

**Comment by 3lvis** [comment]
You forgot to make things public and doesn't seem like it works with NSData.

**Comment by onmyway133** [comment]
@3lvis sorry, I just made the function public. About NSData, you mean after converting it to String, it still does not work ?

**Comment by onmyway133** [comment]
@3lvis I added the test, and it seems to work 😁 

``` swift
let data = "https://www.google.com".dataUsingEncoding(NSUTF8StringEncoding)
XCTAssertEqual(MD5(String(data: data!, encoding: NSUTF8StringEncoding)!),
                   "8FFDEFBDEC956B595D257F0AAEEFD623")
```
